# Start messaging broker
rabbitmq:
  image: tutum/rabbitmq
  dns: ["8.8.8.8"]
  environment:
    - "RABBITMQ_PASS=Phaish9ohbaidei6oole"

# Start image processing worker
imageprocessing:
  build: ./image-processing
  volumes:
    - ./scripts/:/opt/open-ocr/
  dns: ["8.8.8.8"]
  links:
    - rabbitmq
  command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor img-proc"

# Start converting pdf worker
# convertpdf:
#   build: ./convert-pdf
#   volumes:
#     - ./scripts/:/opt/open-ocr/
#   dns: ["8.8.8.8"]
#   links:
#     - rabbitmq
#   command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor convert-pdf"

# Start OCR worker
openocrworker:
  build: ./ocrworker
  volumes:
    - ./scripts/:/opt/open-ocr/
  dns: ["8.8.8.8"]
  links:
    - rabbitmq
  command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

# Start http server
openocr:
  image: maiduchuy/open-ocr
  dns: ["8.8.8.8"]
  volumes:
    - ./scripts/:/opt/open-ocr/
  links:
    - rabbitmq
  ports:
    - "9292:9292"
  command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
